spring:
  datasource:
    url: jdbc:oracle:thin:@//0.0.0.0:1521/XEPDB1
    username: system
    password: SysPassword1
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    url: jdbc:oracle:thin:@//0.0.0.0:1521/XEPDB1
    user: system
    password: SysPassword1
    locations: classpath:/db/migration

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
